
server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coursesystem?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 5224086abc

  jackson:
    time-zone: Asia/Shanghai

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.rainng.coursesystem.model